### PR TITLE
feat: fix incompatible trait implementation with Casbin-rs 2.1.0

### LINKED ISSUE #83: Incompatible trait implementation with Casbin-rs 2.1.0
After updating casbin-rs from 2.0.9 to v2.1.0 there is a compilation failure due to modified trait definition for `Adapter` introduced in https://github.com/casbin/casbin-rs/commit/7d909e8eabfeccb601e89871bebae9f5063336d2

### PR DESCRIPTION
**Pull request by Peterburnett**
Closes #83

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Peterburnett plz fix:

image

**Comment by Peterburnett** [comment]
The failing item is not from my PR, and is unrelated. Happy to add a commit to fix later on today.

**Comment by Peterburnett** [comment]
@hsluoyz I've pushed a fix  for the clippy error. Can you please kick off the CI run again?
Thanks!

**Comment by hsluoyz** [comment]
@Peterburnett thanks. It got fixed.

Another issue showed up:

image

**Comment by Peterburnett** [comment]
@hsluoyz this is not from my code as far as I can tell, and I have no idea what the CI implementation/best practices are for this project. I don't think I am in the best position to fix the MacOS dependencies, as I am not a mac user or have experience managing python toolchains

**Pull request merged**
