### PR TITLE
fix table default values

### PR DESCRIPTION
**Pull request by MATRIXKOO**
Signed-off-by: MATRIXKOO <matrixkook@outlook.com>
modified casbin_rules to casbin_rule and ptype to p_type.

Fix: https://github.com/casbin-rs/diesel-adapter/issues/17

### CODE REVIEW

**Comment by hackerchai** [comment]
@MATRIXKOO Thaks for your work! Can you also alter the table name and column name in Github Actions CI?

**Comment by MATRIXKOO** [comment]
Got it.

**Comment by MATRIXKOO** [comment]
Pls don't close this PR , I'm fixing the CI error.

**Comment by hsluoyz** [comment]
Closed as stale.

**Pull request closed without merging**
