### PR TITLE
bump casbin version

### PR DESCRIPTION
**Pull request by GopherJ**

### CODE REVIEW

**Comment by GopherJ** [comment]
@hsluoyz could you review it?

**Comment by hsluoyz** [comment]
Hi @GopherJ `dump` version is a typo, should be `bump`, see: https://stackoverflow.com/questions/4181185/what-does-bump-version-stand-for

**Comment by GopherJ** [comment]
@hsluoyz  Thanks for pointing out. Fixed.

**Comment by hsluoyz** [comment]
Hi @GopherJ , can you post one of your GSoC ideas here: https://github.com/casbin/SummerOfCode2020 as a potential Casbin-RS mentor?

**Comment by GopherJ** [comment]
Ok I'll do that today

**Comment by hsluoyz** [comment]
Thanks!

**Pull request merged**
