### PR TITLE
ci: add test for multiple os

### PR DESCRIPTION
**Pull request by greenhandatsjtu**
Test project on multiple operating systems via matrix.
ref: https://github.com/casbin/casbin-rs/issues/234
credit to: https://github.com/diesel-rs/diesel/blob/0c6219f5bd9641eea09c6fa7dca4995aefda30a0/.github/workflows/ci.yml

### CODE REVIEW

**Comment by hsluoyz** [comment]
@hackerchai @PsiACE

**Comment by hackerchai** [comment]
@greenhandatsjtu Can you also make a PR to https://github.com/casbin-rs/sqlx-adapter/ ?

**Review by PsiACE — APPROVED** [review]
LGTM

**Comment by greenhandatsjtu** [comment]
> @greenhandatsjtu Can you also make a PR to [casbin-rs/sqlx-adapter](https://github.com/casbin-rs/sqlx-adapter/) ?

Sure, I've been working on it for a while, will make a PR this week.

**Pull request merged**
